### ISSUE TITLE
Asking to edit a rule that is already open, but not saved, accidentally creates a new rule

### ISSUE THREAD

**Issue by iislucas** [zxcalc/quantomatic#100]
Example: 
1. Create a new rule. 
2. Add stuff. 
3. Click on another rule. 
4. Right-click on the first rule and select edit. 
What the hell? Now I have a new rule. :)

**Comment by randomguy3** [comment]
Well, generally, if you try to edit a rule twice, you will get two copies of it to edit.  The last one to be saved "wins".

**Comment by iislucas** [comment]
They seem to get different names. So one ends up with some rules that are not in the ruleset. Pretty confusing. I suggest if you try to edit a rule that's open, you just go to the version of it that is open.
