### ISSUE TITLE
Unclear from practical is users should be using directed or undirected edges

### ISSUE THREAD

**Issue by iislucas** [zxcalc/quantomatic#103]
Clarify if the rules are really wanting to be ones with directed edges & clarify that edge direction has to match. Probably best to simply say: don't turn on the show edge direction, and don't use directed edges.

**Comment by akissinger** [comment]
Clarified. We do want edge direction. Partly because it fits the curriculum better, and partly so people can't cheat by using the built-in red-green theory. :)
