### ISSUE TITLE
Fix bang-box rules matching bang-box graphs

### ISSUE THREAD

**Issue by iislucas** [zxcalc/quantomatic#106]
Match should happen (bang box can be copied, names get copied fresh). But it doesn't happen. This is an issue for the confluence example where the student might write exactly the thing below. Probably not a serious issue for the practical, but algorithm needs some thinking I guess.

![Screen Shot 2013-02-23 at 23 33 22](https://f.cloud.github.com/assets/415450/189220/88e3d4ca-7e55-11e2-8493-84448049f314.png)
![Screen Shot 2013-02-23 at 23 40 18](https://f.cloud.github.com/assets/415450/189221/88fe3c34-7e55-11e2-93c1-d10bffbd1456.png)

**Comment by akissinger** [comment]
This is not a bug. The current matching algorithm only operates on concrete graphs.

**Comment by iislucas** [comment]
In that case you probably want to say so in the practical :) 
(de-tag this from documentation bug if/when you're happy with that, and change the milestone to whatever you think is appropriate too)

I'll change this to a core-feature proposal for core instead of a core-bug.

**Comment by akissinger** [comment]
Done!
