### ISSUE TITLE
Sort out the output of CDATA

### ISSUE THREAD

**Issue by benjaminfrot** [zxcalc/quantomatic#11]
Output_user_data is currently using a modified version of Isabelle's XML lib.
Would be better to keep everything in Quanto and not have to modify the General/xml.ML

**Comment by randomguy3** [comment]
Or, even better, can we push the modification to General/xml.ML to the right places?  CData support is, after all, something with more general applications.

**Comment by iislucas** [comment]
CData is now managed as Text in XML.ML. I've made changes to no longer use CDATA and instead use Text for vertex name output, so now closing this issue.
