### ISSUE TITLE
Failed to communicate with core process

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#113]
Rebuilt the new quantomatic as per Alex M's recent email.  When I try to add a vertex to the empty graph I see the following.
![screen shot 2013-07-11 at 14 52 58](https://f.cloud.github.com/assets/1511888/781665/4b073080-ea29-11e2-9b64-a481c89d2d5b.png)

Stack trace is below.

---

run.gui:
     [exec] Running: export PATH="/Users/drd/Code/quanto/quantomatic/core/bin/:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/usr/texbin:/usr/X11/bin:/Users/drd/bin:/Users/drd/src/Isabelle/bin:/usr/local/bin:" && java -jar /Users/drd/Code/quanto/quantomatic/gui/dist/QuantoGui.jar 
     [exec] 
     [exec] 11-Jul-2013 14:36:59 quanto.gui.QuantoApp main
     [exec] FINER: Starting quantomatic
     [exec] 11-Jul-2013 14:36:59 quanto.gui.QuantoApp main
     [exec] FINE: Using dot executable: dot
     [exec] 11-Jul-2013 14:36:59 quanto.gui.QuantoApp main
     [exec] FINE: Using core executable: quanto-core
     [exec] 11-Jul-2013 14:36:59 quanto.core.protocol.CoreProcess startCore
     [exec] FINEST: Starting quanto-core...
     [exec] 11-Jul-2013 14:36:59 quanto.core.protocol.CoreProcess startCore
     [exec] FINEST: quanto-core started successfully
     [exec] 11-Jul-2013 14:36:59 quanto.core.protocol.CoreTalker connect
     [exec] FINE: The core is running version 1.0 of the protocol
     [exec] 11-Jul-2013 14:37:02 quanto.core.ConsoleInterface <init>
     [exec] FINEST: Retrieving commands...
     [exec] 11-Jul-2013 14:37:02 quanto.core.ConsoleInterface <init>
     [exec] FINEST: Commands retrieved successfully
     [exec] 11-Jul-2013 14:37:02 quanto.gui.QuantoApp main
     [exec] FINER: Finished initialisation
     [exec] Protocol error: > not ;
     [exec] Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
     [exec]     at quanto.core.protocol.ResponseReader.parseNextResponse(Unknown Source)
     [exec]     at quanto.core.protocol.CoreTalker.getResponse(Unknown Source)
     [exec]     at quanto.core.protocol.CoreTalker.getJsonResponse(Unknown Source)
     [exec]     at quanto.core.protocol.CoreTalker.addVertex(Unknown Source)
     [exec]     at quanto.core.Core.addVertex(Unknown Source)
     [exec]     at quanto.gui.InteractiveGraphView.addVertex(Unknown Source)
     [exec]     at quanto.gui.InteractiveGraphView$36.actionPerformed(Unknown Source)
     [exec]     at quanto.gui.InteractiveGraphView.commandTriggered(Unknown Source)
     [exec]     at quanto.gui.SplitGraphView.commandTriggered(Unknown Source)
     [exec]     at quanto.gui.ViewPort.executeCommand(Unknown Source)
     [exec]     at quanto.gui.Toolbox$AddVertexArea$2.actionPerformed(Unknown Source)
     [exec]     at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
     .....
Much swing/awt stuff cut from here
   ....
     [exec]     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
     [exec]     at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
     [exec] 11-Jul-2013 14:52:19 quanto.core.protocol.CoreTalker writeFailure
     [exec] SEVERE: Failed to write to core process; last received message was "[B@3d057305[B@3d0573052758[B@30c26c8f[B@30c26c8f271242762"
     [exec] 11-Jul-2013 14:52:51 quanto.core.protocol.CoreTalker writeFailure
     [exec] SEVERE: Failed to write to core process; last received message was "[B@3d057305[B@3d0573052758[B@30c26c8f[B@30c26c8f271242762"
     [exec] 11-Jul-2013 14:53:30 quanto.core.protocol.CoreTalker writeFailure
     [exec] SEVERE: Failed to write to core process; last received message was "[B@3d057305[B@3d0573052758[B@30c26c8f[B@30c26c8f271242762"
     [exec] 11-Jul-2013 14:53:59 quanto.core.protocol.CoreTalker writeFailure
     [exec] SEVERE: Failed to write to core process; last received message was "[B@3d057305[B@3d0573052758[B@30c26c8f[B@30c26c8f271242762"

**Comment by randomguy3** [comment]
Hrm.  How did you start quantomatic?  It sounds like the GUI wasn't rebuilt properly.

Can you try updating (I did just fix something, but not this issue), then doing a clean rebuild:
cd core && make clean && make &&
cd ../gui && ant clean && ant
then run Quantomatic again?

**Comment by rossduncan** [comment]
OK, I haven't done any further testing, but it doesn't fail at the first hurdle now.

I am running it, as per your email, by ant run.gui.

-r

**Comment by randomguy3** [comment]
Well, I guess we'll chalk that up to "ant's dependency tracking kinda sucks".

**Comment by randomguy3** [comment]
Huh, I was unfairly blaming ant.  It was actually our gui/build.xml, which was calling "make bin" when the "bin" target no longer exists.  Latest integration fixes this.
