### ISSUE TITLE
Tikz export

### ISSUE THREAD

**Issue by akissinger** [zxcalc/quantomatic#125]
Support tikz export graphs, rules, and derivations. For graphs and rules, output a single, tikzit-readable .tikz file. (In the latter case, include an equals sign in a blank node in the middle).

For derivations, there should be the option to output either a single latex file with many tikz figures laid out nicely, or a directory of tikz files along with a latex file that includes them (again, laid out nicely) via \tikzfig.

In either case, quanto should be smart about where to insert line breaks. For these kinds of derivations, it is typical to have 3-5 steps per line. Ideally, it should either figure out automatically how many steps to pack into a line or use a latex environment that puts breaks in decent places. "dmath" might do an okay job of this.

**Comment by zamdzhiev** [comment]
@akissinger 
I am currently working on this issue and have done some commits which correctly draw the vertices. However, for, best results, I think that tikzit should provide a set of good defaults for the predefined shapes. For example, green and red nodes are OK, we can just export them as

`\node [style=gn] (v4) at ...`
`\node [style=rn] (v5) at ...`

However, for wire vertices, there is no predefined style. Similarly, for !-box nodes.

**Comment by zamdzhiev** [comment]
Closing this issue. File new issues if there are bugs or needed features missing.
