### ISSUE TITLE
Snap to grid

### ISSUE THREAD

**Issue by akissinger** [zxcalc/quantomatic#126]
Add an option for snapping graphs to grid. This will be important for getting decent tikz output (issue #125).

One potential issue to watch out for is how this interacts with the layout engine. Currently, the user can hold down R with some vertices selected to "relax" their positions. The snap should happen after the relax is done, otherwise nothing can move!

**Comment by zamdzhiev** [comment]
The above commit (58c2f0bdfc02aeeb4748d2f324d4fc4d01e784cb) fixes this. It adds an entry to the Edit menu. When pressed, all vertices are snapped to a square grid with size 0.25 (recognised by Tikzit). Shortcut is `Ctrl+G`

**Comment by akissinger** [comment]
Doesn't seem to be working for derivations. Also, there should be a mode that continuously snaps to grid, i.e. adding a new menu item "Enable/disable snapping".
