### ISSUE TITLE
Shortcut for some entries in Edit Menu are not shown

### ISSUE THREAD

**Issue by zamdzhiev** [zxcalc/quantomatic#136]
Cut, Copy, Paste and Snap to Grid have working shortcuts, but they are not shown in the
Edit Menu and are therefore hard to discover by users. However, the shortcuts for Undo and Redo are shown.

**Comment by zamdzhiev** [comment]
Fixed by removing the shortcuts from GraphEditController and enabling them in the menu itself

**Comment by akissinger** [comment]
Reverted this change, since it clobbers copying from derivation. Perhaps we should just remove these menu items, since copy/paste is very focus-sensitive.
