### ISSUE TITLE
Fast normalise should be cancellable

### ISSUE THREAD

**Issue by randomguy3** [zxcalc/quantomatic#15]
The loop in "fast normalise" is entirely in the GUI, so it should be possible to do some threading magic to allow the user to cancel it if it is taking too long.

Possibly something like the "rewriting" bar when doing an ordinary normalisation, but in the middle of the graph view?

Need to consider interleaving commands, I guess - what happens if the user does something else while this is happening.  What happens with ordinary normalisation?  What if the user tries to change the theory?

Modal dialog is a possibility (although dialogs are generally not very nice).

**Comment by randomguy3** [comment]
This probably belongs in InteractiveGraphView, although modifications to quanto.core.Core.fastNormalise will be necessary.

**Comment by randomguy3** [comment]
Use the Job class and InteractiveView.showJobIndicator()

**Comment by zamdzhiev** [comment]
the new GUI can stop the normalisation process
