### ISSUE TITLE
Simprocs could be "run once" or "run consistently"

### ISSUE THREAD

**Issue by hmillerbakewell** [zxcalc/quantomatic#160]
Simprocs could be set to run once and then stop (giving feedback) or run every time the user performs a manual rule application (again needing to give feedback)

**Comment by akissinger** [comment]
Not sure this is a good idea. It seems like things will get out of control very easily. What would be useful is a hotkey for "run last simproc". I could imagine you'd want to do something like "RULE - spider everything - RULE - spider everything - RULE - ....". Having a hotkey would make this go very smoothly.

**Comment by hmillerbakewell** [comment]
"Re-run last simproc" is now a menu item, and is currently bound to "ctrl+space"
