### ISSUE TITLE
creating new files does not always focus the correct tab

### ISSUE THREAD

**Issue by akissinger** [zxcalc/quantomatic#164]
When a new file is created (e.g. New Graph, New Axiom, or Start Derivation), it gives focus to the wrong tab whenever there are "Untitled" tabs. Which tab it does give focus to seems to depend on the number of untitled tabs.

**Comment by hmillerbakewell** [comment]
The UI has been reworked since this bug was reported and this bug cannot be reproduced. Please re-open or create new a new issue if this persists after the next major update (expected before 2018-05-07)
