### ISSUE TITLE
[ERROR] Failed to construct terminal; falling back to unsupported

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#168]
When launching quanto from the command line - via `sbt run` - I get this error and a stack trace.

```
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  ...
```

I'm using the terminal that ships with Mac OS X.

**Comment by rossduncan** [comment]
I left out a very important detail:  Quanto still starts and appears to work fine!  It just barfs all this into the terminal on its way.

commit : edca935890e6e7d626fdc470eb8e29db76ccea71
I have 
``` 
$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode) 
```

**Comment by hmillerbakewell** [comment]
Does this still happen? I can't test on OSX I'm afraid.

**Comment by hmillerbakewell** [comment]
This doesn't appear to be causing any problems, so I'm closing it for now since we've done a major UI update (a likely source of the error.) Please re-open or create new a new issue if this persists after the next major update (expected before 2018-05-07)
