### ISSUE TITLE
When a tag is selected in the RulesBar, should other tags be deactivated?

### ISSUE THREAD

**Issue by randomguy3** [zxcalc/quantomatic#17]
It is unintuitive to have active rules that you can't see.  So the natural thing would be to disable all other rules when you switch to a tag.

HOWEVER, we also don't want the active rule set to be changed if a user switches to a tag and back again.

The ideal behaviour is:
user switches to a tag -> only the intersection of the previously-active rules and the rules in the selected tag are active
user switches back to "All rules" -> exactly the same rules are active as were before switching to the tag, except for those where the user has explicitly enabled/disabled rules while in the tag view

So all->tag->all should have no effect
all->tag->disable rule1->all should be the same as all->disable rule1
all->tag->enable rule1->all should be the same as all->enable rule1

Not sure how best to implement this.

**Comment by zamdzhiev** [comment]
not relevant for new gui
