### ISSUE TITLE
Choose the default direction of new lemmas

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#170]
When a new theorem is saved the user should have the option of having it in the forward or backward direction by default.

(VERY often the backward direction is the one you want -- it's a pain to have to reverse all those rules, and also makes the names stupid.)

**Comment by hmillerbakewell** [comment]
Saving a derivation now puts you straight to a rule page showing the rule, and there is now a "Rule" menu that includes inverting the rule you are looking at.
