### ISSUE TITLE
Cancelled simprocs continue updating view

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#175]
If a (runaway) simproc is cancelled, and the proof brought back to an earlier point, the simproc may continue to update the left pane of the derivation window with bogus graphs.  This can continue for minutes after the proc was cancelled.

To reproduce: make a simproc which obviously diverges e.g. reduce inverse spider, let it run for 30 seconds and cancel it.  Now delete the proof head back the point before the simp proc was run.

**Comment by akissinger** [comment]
I think this is fixed now, so closing. @hmillerbakewell : re-open this if I'm wrong.
