### ISSUE TITLE
Sometimes mouse focus gets stuck on a vertex

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#177]
Sometime after you drag a vertex in the graph editor it stays stuck, so no amount clicking will cause the vertex to be released form the point and very click is interpreted as trying to drag the vertex to a new location.

**Comment by akissinger** [comment]
I think this dumps a stack trace to the terminal when this happens. If you get this, could you paste the stack trace here?

**Comment by hmillerbakewell** [comment]
The UI has been reworked since this bug was reported and I can't reproduce this. @akissinger do you think this is safe to close for now?
