### ISSUE TITLE
UndoStack not registered for first opened document

### ISSUE THREAD

**Issue by jvdwetering** [zxcalc/quantomatic#179]
If you open a single document you can't undo stuff. I've managed to pinpoint this to currentDocument not updating before the SelectionChanged event is called, but I don't know how to fix it.

**Comment by akissinger** [comment]
This was still happening on integration. Now fixed on qpc2018 branch by adding a call to MainDocumentTabs.publishChanged() to addAndFocusPage(). Will close when I merge.
