### ISSUE TITLE
Theory editory doesn't create good default_data

### ISSUE THREAD

**Issue by akissinger** [zxcalc/quantomatic#194]
The default_data field of a given type in a theory needs to look something like this:

"default_data": { "type": "Z", "value": "" }

In particular, it must give values for "type" and "value", even though we can guess the type already. This is a bit redundant, but quanto expects this field to be there, so it either needs to beincluded, or quanto needs to pull this type field from somewhere else if it doesn't find it when loading a graph.

**Comment by hmillerbakewell** [comment]
Slightly misleading commit title: Nodes are _now_ created with default data.

In the future this should probably be changed: The default data on the node shouldn't need to know the node's name (redundant duplication of data) as the theory should handle that.
