### ISSUE TITLE
Suggestion: don't create lots of wire vertices in "freehand draw" tool

### ISSUE THREAD

**Issue by akissinger** [zxcalc/quantomatic#210]
I can't really see the use case of having long, squiggly edges with loads of wire vertices on them. It seems more sensible to have the freehand draw tool have the same mouse up/mouse down behaviour when creating nodes/boundaries/edges, but stop periodically inserting wires. This may also mean we no longer need the "simplify" button, which has its own issues (see #209).

**Comment by hmillerbakewell** [comment]
Agreed and changed - although I have left the "simplify" button in there for now.

**Comment by akissinger** [comment]
I think that's okay. A good use for minimise is the following: if you decide you want to plug a graph G into H, you can copy G to clipboard, paste into H, freehand connect up to the wires, then click minimise.

Alternatively, you could auto-minimise every time an interior wire vertex is created. Though you need to be especially careful with the undo logic here...
