### ISSUE TITLE
Simproc API docs are 404

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#224]
Help menu item "Simproc API" opens the URL 
[https://quantomatic.github.io/SimprocAPI.html](https://quantomatic.github.io/SimprocAPI.html)
but this address is 404.

**Comment by hmillerbakewell** [comment]
The intergration branch has a fixed link. The top banner of the site does obscure the text a little: @akissinger should we keep the banner as is?

Go to https://quantomatic.github.io/#SimprocAPI to see what I mean.

**Comment by akissinger** [comment]
Can this be fixed by shifting the anchor up a bit and/or adding some extra &lt;br&gt;s?

**Comment by hmillerbakewell** [comment]
Shifted the anchor via CSS, so it adds an extra 300px above wherever it is in the text. It will be pushed along with the other updates for the new release.
