### ISSUE TITLE
Loaded simprocs do cannot be refreshed after edit

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#226]
If you have a simproc loaded, and you edit either the python code OR any of the rules used by the simproc then the loaded simproc does not see the change and there is no way to reload it other than restarting quanto.

This is a major pain in the ass.

**Comment by akissinger** [comment]
Do you mean, if you click "play" again, after editing python OR rules, the simproc is still not refreshed?

**Comment by rossduncan** [comment]
Eh, I thought I tried that but apparently not.  Sorry!

SPURIOUS REPORT.
