### ISSUE TITLE
Shortcut keys

### ISSUE THREAD

**Issue by akissinger** [zxcalc/quantomatic#29]
These are inconsistent. For example, hitting 'E' opens undirected edge mode, but doesn't change tool. Would be good to have (displayed somewhere) hotkeys for all three.

**Comment by zamdzhiev** [comment]
The new GUI (derive) is currently missing shortcut keys for graph editting

**Comment by zamdzhiev** [comment]
Commit b7d066b20c03ef4e12766c721953b8839ca36dd8 adds some shortcuts for graph editing. I think it is a good idea to also add some shortcuts for derivations for manipulating the proof tree etc.

**Comment by zamdzhiev** [comment]
Closing this issue. The only buttons missing shortcuts are those for navigating the proof tree when doing derivations. However, doing this with the mouse is pretty fast anyway as all buttons are next to each other. It might get more confusing if we add shortcuts for this in my opinion.

Open up a new issue if there are shortcuts missing or if you feel this should be reevaluated.
