### ISSUE TITLE
Crash when rewriting

### ISSUE THREAD

**Issue by randomguy3** [zxcalc/quantomatic#31]
Attempting to rewrite can sometimes crash the core:

06-Mar-2012 16:39:39 quanto.core.protocol.LoggingOutputStream writeLog
FINEST: Sending message to core: ¤<WO¤:165¤|miriam_test-graph¤;8¤:Vb¤,Ve¤,Vh¤,Vc¤,Va¤,Vg¤,Vd¤,Vf¤>
06-Mar-2012 16:39:39 quanto.core.protocol.LoggingInputStream writeLog
SEVERE: Received invalid message: "
"
06-Mar-2012 16:39:39 quanto.core.protocol.ProtocolReader consumeStream
INFO: Discarding data: "Exception trace for exception - ename_already_exists_exp raised in graph.ML line 361

ProtocolInterface.run_in_textstreams(2)run_in_textstreams'(1)
ProtocolInterface.run_in_textstreams(2)
run(1)
End of trace

"

**Comment by randomguy3** [comment]
See https://gist.github.com/1987403 for the files

**Comment by randomguy3** [comment]
May be related to issue #28.

**Comment by rossduncan** [comment]
Is the the same issue as I reported on email at the weekend?  I can't tell from the files.
