### ISSUE TITLE
reorder rules in ruleset

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#35]
Fast normalise should pick rules in the order the are listed in the ruleset.  This order should be changable.

**Comment by akissinger** [comment]
Right now rules are ordered according to their name. So a quick hack would be to encode the ordering in the names of rules. Course, this would help: (issue #45)

**Comment by randomguy3** [comment]
Are you sure they are ordered according to their names, and not according to a hash based on their names?

**Comment by randomguy3** [comment]
Also, I think this is 2.1 material.  2.0 is the minimum required to make it as usable as 1.0 was.

**Comment by akissinger** [comment]
no longer relevant with simprocs in QuantoDerive
