### ISSUE TITLE
create rule from rewrite sequence

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#36]
We should make an easy way to create a new rule based on a rewrite sequence.  I imagine it working like this: make a graph;  press "record"; do rewrites; press "stop record"; a pop-up now prompts for the name of the new rule, and adds it to the rule set.

As a first attempt, the process should complain if the user tries to do anything other than rewrites: i.e. add nodes etc.  I can imagine smarter things for later iterations of this feature.

**Comment by randomguy3** [comment]
Shunted to 2.1, as this is not something we really need for a 2.0 release.

Note that copy-and-paste can be used to simulate this (create a new rule, copy in graph to LHS, rewrite original graph, copy to RHS).

**Comment by rossduncan** [comment]
Alex if you try to simulate this as you suggest, you are quite likely to hit the "boundaries and !-boxes must match" error.  Since there is (at present) no way to rename boundary nodes this there is no work around.

**Comment by randomguy3** [comment]
Huh.  Looks like renaming hasn't been merged in from the practical branch yet.

**Comment by akissinger** [comment]
Superceded by #118.
