### ISSUE TITLE
new rule via reversing old rule

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#37]
It should be possible to create a new rule by reversing an existing rule - i.e just exchanging the left- and right-hand sides.

Right-click on rule; "New rule by reverse", prompt for name (prepopulate field with "old-name-rev"); add rule to rule set.

**Comment by randomguy3** [comment]
Shunted to 2.1, as I don't think it's essential for a stable release.

**Comment by rossduncan** [comment]
This one also can't be done via cut and paste due to boundary node naming issues.
