### ISSUE TITLE
Renaming edge nodes and !-boxes

### ISSUE THREAD

**Issue by randomguy3** [zxcalc/quantomatic#4]
It should be possible to rename edge nodes and !-boxes when creating rules

**Comment by rossduncan** [comment]
Why is this closed?  I don't see anyway to rename boundary nodes.

**Comment by benjaminfrot** [comment]
Originally this was something we wanted for the practical. So I pushed it on the practical branch. 
Once user_data is re-implemented (in a different way in master), I will merge all the commits that are in the practical branch to master.
