### ISSUE TITLE
"Thinking" indicator when core busy

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#40]
The core often takes quite a long time to generate the list of rewrites, but the gui gives no indication that this is what's happening, as opposed to I just didn't press the key hard enough.  FIX: make some visible indicator that the gui is waiting for the core.

**Comment by randomguy3** [comment]
Short term: just display something saying "working".

Long term: use threads to not block the GUI.

**Comment by randomguy3** [comment]
I've come to the conclusion that there is no sane way of doing this in Java without messing around with threads, so I'm inclined to shunt it to 2.1.

**Comment by zamdzhiev** [comment]
such a feature exists in new GUI
