### ISSUE TITLE
Export rewrite sequences

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#42]
It would very useful if a rewrite sequence from quanto could be exported (perhaps as tikz compatible with Tikzit) so that proofs done in quanto can be used in publications.  A bare sequence of graphs would be the minimum useful thing, but extra information that would be useful would be:
- name of the rule used at each step
- indication of where the rule matched in the LHS
- graphical representation of the rule instance used.

**Comment by randomguy3** [comment]
This is something that will go into the new GUI that Aleks and Vladimir are working on.

**Comment by akissinger** [comment]
see QuantoDerive
