### ISSUE TITLE
rewriting and undo

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#43]
There seems to be a lot of spurious undo steps.  When I do a rewrite and then press undo, it doesn't undo the rewrite, it just fucks around with the layout.  After about 10 undos I get back to the graph I had before the rewrite, although the layout is now screwed up.

**Comment by rossduncan** [comment]
Probably related to https://github.com/Quantomatic/quantomatic/issues/5

**Comment by akissinger** [comment]
Yes. The multiple-undo issue should be handled by implementing "begin undo group" and "end undo group" functions in the core. Does the layout issue happen when you press undo too quickly? The graph isn't currently being locked properly, so if the graph changes while the GUI is still updating the vertex positions, things get mangled. You'll usually see some complaining on the console if this is the case.

**Comment by rossduncan** [comment]
So a quick test reveals the following.  I use the "remove-H" rule, which replaces one vertex with three.  Pressing undo 3 times just results in layout changes to the rewritten graph.  The fourth time actually reverses the rewrite.  A fifth undo restores the layout I had before.  I guess more complex rewrites will result in more steps.

This is all being done slow enough that nothing is complaining.

Clearly, the right thing is one user action = one undo step

**Comment by akissinger** [comment]
I agree with the one-action-one-undo for 95% of things, but it's less obvious in the case of (non-fast) normalising. Ideally, there should be a command that undoes individual rewrite steps as well as jumping all the way back to the beginning of the normalise procedure.

**Comment by rossduncan** [comment]
Yes.  Another case where it may be the wrong thing is when I do a rewrite, but the layout is shit and I can't see what I've got, so I move the vertices around so I can see what's going, then realise I don't like that rewrite and have to back out a hundred layout changes before I get back to where I started.

**Comment by akissinger** [comment]
Maybe the best solution is to have a separate "Undo most recent rewrite(s)" command, that rolls back to the state before the last rewrite (in the case of a single rewrite) or before a normalise (in the case of normalise or fast normalise). Core would need to annotate the undo stack with this data, but it shouldn't be too difficult. This is probably a 2.1 feature, whereas having sensible undo grouping should be done by 2.0.

**Comment by benjaminfrot** [comment]
User data has now been re-implemented in a feature branch and this bug should now be fixed. (Cherry picked as soon as the build is fixed in 'Integration'....)
I leave the issue open since the 2.1 condition is not met yet, but clear the 2.0 milestone.

**Comment by benjaminfrot** [comment]
Aleks: Your idea has been implemented. It is now possible to undo/redo rewrites, using the ctrl + shift + z (resp ctrl + shift y).

(I made a typo in the commit message and it is not referenced here, so here it is: https://github.com/Quantomatic/quantomatic/commit/e84410b210452d86f95d1b3bc8cf29a992120edb )
