### ISSUE TITLE
make the separator a bit darker or something

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#46]
The separator between the graph view and the rule list needs to be a bit more visible.  The number of times I've resized the rule list instead selecting the graph is getting annoying.

**Comment by benjaminfrot** [comment]
I can't really tell how it renders on Mac. So I made it a bit thicker. Tell me if that makes things better.
It looks ok to me on Linux, with the open JVM.

**Comment by rossduncan** [comment]
Thicker doesn't help.  The problem is that it's the same colour as the graph view.  It should be made darker, or put a dark line at its boundary.

**Comment by benjaminfrot** [comment]
I changed the color and it's now dark grey. That should solve it. Pushed only to 'practical' for now as 'integration' seems broken. 
Stays open, will be cherry-picked out soon.
