### ISSUE TITLE
unification and fresh names

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#47]
If you have a rule where the LHS has a vertex is labelled a+b, and in the RHS a and b occur on different vertices, when the rule is matched, "a" will grab whatever is labelling the vertex and the rewritten graph will contain "b" as a variable.  If you apply the rule multiple times _the same b_ will occur multiple times.  If b is already in the graph it makes no difference.

Solution: need to check if b already occurs and use a fresh name in this situation.

**Comment by iislucas** [comment]
Fine-grained control of variables names is possible, but it is easier to simply rename rule graphs so the vertex-variables are disjoint between the rule and the target graph. This is what I'm going to implement...

**Comment by iislucas** [comment]
OK, graphs now have their internal variables renaming prior to matching/rewriting, unit test for renaming added too.
