### ISSUE TITLE
Deal with theories with external files not in the same dir

### ISSUE THREAD

**Issue by randomguy3** [zxcalc/quantomatic#53]
Currently, when we save a local copy of the active theory and its dependent files, we only save local copies of its dependent files (eg: SVG files) when they reside in the same directory as the theory file.  This will break things with any other arrangement, but thought needs to be given to how this will work.

The most obvious solution is to actually re-generate the theory file with the paths changed.

**Comment by zamdzhiev** [comment]
refers to old GUI
