### ISSUE TITLE
Do something sensible when the core crashes

### ISSUE THREAD

**Issue by randomguy3** [zxcalc/quantomatic#54]
There's no point trying to continue and just throwing up errors.  The GUI should either quit itself, or try to restart the core (and clear the state from the last instance of the core).

**Comment by zamdzhiev** [comment]
In Derive, when the core crashes, we can still save the state, but we can't do any other rewrites ( which is OK). Also, there's a bug where the core status doesn't change. It would also be nice to be able to start/stop/restart the core from the GUI.
