### ISSUE TITLE
Add an icon for boundary/edge vertices

### ISSUE THREAD

**Issue by randomguy3** [zxcalc/quantomatic#56]
Also: should we call them "edge vertices" rather than "boundary vertices"?

**Comment by rossduncan** [comment]
I prefer the term boundary, since they have rather different properties (w.r.t.) the way that quanto works than the edge points of the open graphs formalism.

**Comment by randomguy3** [comment]
OTOH, I think they _should_ work a little more like edge points.  There are some matching quirks that need to be worked out in quanto core (it still doesn't deal with self-loops quite as it should, for example).  It should be possible, however, to put a boundary/edge point in the middle of an edge and put a !-box around it, though, to indicate that the edge can be copied.
