### ISSUE TITLE
Quantomatic is slow at starting up

### ISSUE THREAD

**Issue by randomguy3** [zxcalc/quantomatic#57]
Can we do something about this?

Fun fact: a full second of startup time on my machine is spent in the SVG library doing font-related work to get the "H" for the hadamard gate.

Also, we spend a couple hundred milliseconds in SmoothLayoutDecorator.prerelax() iterating over QuantoForceLayout on a new graph - when there are no vertices to lay out!

NB: low priority

**Comment by zamdzhiev** [comment]
refers to old GUI
