### ISSUE TITLE
Projects/Workspaces

### ISSUE THREAD

**Issue by randomguy3** [zxcalc/quantomatic#61]
We should probably provide a way to tie together a session (graphs etc), and call this something like a project or a workspace.  Each project/workspace should be linked to a theory, but you can have more than one project/workspace using the same theory.

Rulesets are ambiguous - do they make more sense tied to theories or projects/workspaces?  I'm tending towards the latter, although it may make sense for a theory to have a default ruleset that is loaded for new projects/workspaces.

**Comment by zamdzhiev** [comment]
fixed in new GUI
