### ISSUE TITLE
Better label placement

### ISSUE THREAD

**Issue by randomguy3** [zxcalc/quantomatic#63]
!-box labels can easily be obscured by edges.  Labels (for both !-boxes and nodes) should be placed intelligently.

**Comment by benjaminfrot** [comment]
Do you know by any chance if the jung framework has any thing that could help with that?
At the moment the position for the labels is set by hand. 
So if we implement that by hand - checking if there is any edge crossing over a label and moving the label to a better location - it looks like it is going to be computationally intensive.

Maybe you had a better solution in mind. Making the edges going out from the sides of the vertices could be one (so we get spiders), but that does not solve the problem for !-boxes and I don't think it would look pretty...

**Comment by randomguy3** [comment]
On 27/03/12 14:05, Benjamin Frot wrote:

> Do you know by any chance if the jung framework has any thing that could help with that?

I don't think it does, but we can edit it to suit our needs (that's why 
I put the sources wholesale into our repo).

> At the moment the position for the labels is set by hand.
> So if we implement that by hand - checking if there is any edge crossing over a label and moving the label to a better location - it looks like it is going to be computationally intensive.

I'm not convinced it would be particularly intensive compared to the 
actual rendering, providing we're caching the right information.

We could even just allow users to drag labels round (or onto) the node, 
so that they set the location manually.  Although I'm not sure how that 
would work with rewriting.

**Comment by akissinger** [comment]
This issue refers to the old version of quantomatic. I don't think this causes any usability issues in the new version.
