### ISSUE TITLE
Crash when rewrite would create a loop

### ISSUE THREAD

**Issue by randomguy3** [zxcalc/quantomatic#65]
Test case:

Theory: red_green

One rule: hh_to_id: takes
bound1 -- H -- H -- bound2
to
bound1 -- bound2
(undirected edges)

Graph: two H vertices with two (undirected) lines between them.

Do "show rewrites" or similar.

Expected result: a boundary vertex with a self-loop.

Actual result:
The core terminated with the following message:

Exception trace for exception - no_such_vname_exp raised in basic_graph.ML line 354

ProtocolInterface.run_in_textstreams(2)run_in_textstreams'(1)
ProtocolInterface.run_in_textstreams(2)
run(1)
End of trace

**Comment by benjaminfrot** [comment]
Hi,
did try to do that in the integration branch?
 I think this is related to issue #8 and I fixed it in the practical branch.
This will be merged soon, along with the patches of feat_br_user_data and practical.

**Comment by randomguy3** [comment]
Yes, I did this in the integration branch.

I think from now on we shouldn't really consider something fixed until it hits integration.
