### ISSUE TITLE
Graph constantly repaints

### ISSUE THREAD

**Issue by randomguy3** [zxcalc/quantomatic#66]
Opening a graph and just leaving Quanto alone causes it to use a lot of CPU, as it repaints constantly.

This may be related to issue #58, but only happens for me when there is a graph with vertices in the foreground (switching to the console or an empty graph makes it go away).

Maybe something to do wtih layout?  Profiling just shows that repainting is happening, not what is causing it.

**Comment by randomguy3** [comment]
Figured out why (sort of).  It's to do with our labelling hack (InteractiveGraphView.QVertexLabeler).  I'm going to see if I can figure out how to deal with editable labels properly.

**Comment by zamdzhiev** [comment]
Not a problem for new GUI (derive)
