### ISSUE TITLE
Tool selection should be per window, not per graph

### ISSUE THREAD

**Issue by randomguy3** [zxcalc/quantomatic#68]
In split graph view, it's really irritating to have to focus a graph before changing the tool.

The tool state should be maintained by QuantoFrame, not by InteractiveGraphView.

**Comment by benjaminfrot** [comment]
Related to #50

Oops, I just saw this issue.
I fixed #50 by modifying split graph view, not QuantoFrame. If you want it to be implemented in QuantoFrame I can do it.
If you're ok with the fix, I guess this issue should be closed. 

( github.com/Quantomatic/quantomatic/commit/e53647a2fac25e9fb999bbc026389cb03a92fdb6 )

**Comment by randomguy3** [comment]
This is fixed for the case where you use the tool buttons at the top, but not where you use the keyboard shortcuts.

**Comment by zamdzhiev** [comment]
refers to old GUI
