### ISSUE TITLE
Matching on subgraph behaviour wrong in 2 ways

### ISSUE THREAD

**Issue by akissinger** [zxcalc/quantomatic#76]
1. subgraph should be expanded out by one node in all directions to include edges in and out. (It used to be like this)
2. matchings should still be valid globally. Right now, it seems to be matching only against the selected subgraph, with the rest of the graph thrown away. This can lead to invalid (i.e. non-full) matchings.

My suggestion:
1. For a subgraph H of G, expand H out by one in all directions to obtain a larger subgraph H'.
2. Find all of the matchings of rules in H' such that the interior of the rule is contained in H.

This is both quick, because it acts locally, and sound, because it respects fullness.

**Comment by randomguy3** [comment]
This _should_ be fixed now.  Because we normalise the graph before matching, we just include the first wire vertex on every wire adjacent to the selected graph.  Can you check?

**Comment by randomguy3** [comment]
Did you have a test case for this?
