### ISSUE TITLE
Insert_graph does not preserve vertex type

### ISSUE THREAD

**Issue by benjaminfrot** [zxcalc/quantomatic#77]
When a graph in which a Z vertex with a variable expression is inserted into another graph, it's type changes to X

Steps to reproduce:
- In the gui, create a Z vertex, set its expression to 'a'
- Select the vertex, ctrl + C, ctrl + V.
  Result:
  The pasted vertex will be of type X and will have its variable name changed to 'b'

Looks like it is related to the recent changes made in order to avoid name clashes when a graph has the same expression names
as the rule been applied.

**Comment by randomguy3** [comment]
We ran into this when debugging for the practical, and fixed it.
