### ISSUE TITLE
Display warnings from matching in GUI

### ISSUE THREAD

**Issue by randomguy3** [zxcalc/quantomatic#84]
The matching can produce warnings (currently only one warning type).  These need to be converted to human-readable messages, returned over the protocol (in some structured form), and displayed to the user.

These should NOT be displayed as modal dialogue boxes.  We could really do with some sort of "rewriting log", I think, that says what matches were found, what rewrites were made and what warnings were produced.

**Comment by hmillerbakewell** [comment]
There's now the UserAlerts module that seems ideal for this.
