### ISSUE TITLE
"New Rule" => "Create Rule" in tex

### ISSUE THREAD

**Issue by iislucas** [zxcalc/quantomatic#96]
In practical branch `docs/cqm_practical/cqm_practical.tex`, the latex/pdf refers to "New Rule" but this is called "Create Rule" (when you hover over the right button) and you don't actually see the name of the rule until you mouse-over and hover. Maybe show pictures of the buttons in the pdf?

**Comment by iislucas** [comment]
Might also be good to mention that you can copy/paste graphs?

**Comment by randomguy3** [comment]
Closing this, as the practical is done.
